MaLopez_Examen1P/Models/ErrorViewModel.cs
namespace MaLopez_Examen1P.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MaLopez_Examen1P/Models/ML_modelo1.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MaLopez_Examen1P.Models
{
    public class ML_modelo1
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(20, ErrorMessage = "El nombre no puede exceder los 100 caracteres")]
        
        public string? MLNombre { get; set; }
        public int MLEdad { get; set; }
        public string? MLDireccion { get; set; }
        [Required]
        public string? MLDepartamento { get; set; }
        public DateTime MLFechaNacimiento { get; set; }
        public bool MLIsCliente { get; set; }
        [Range(0, 1000000)]
        public decimal MLSaldo { get; set; }

    }
}

MaLopez_Examen1P/Controllers/HomeController.cs
using MaLopez_Examen1P.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MaLopez_Examen1P.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MaLopez_Examen1P/Controllers/ML_modelo1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MaLopez_Examen1P.Data;
using MaLopez_Examen1P.Models;

namespace MaLopez_Examen1P.Controllers
{
    public class ML_modelo1Controller : Controller
    {
        private readonly MaLopez_Examen1PContext _context;

        public ML_modelo1Controller(MaLopez_Examen1PContext context)
        {
            _context = context;
        }

        // GET: ML_modelo1
        public async Task<IActionResult> Index()
        {
            return View(await _context.ML_modelo1.ToListAsync());
        }

        // GET: ML_modelo1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mL_modelo1 = await _context.ML_modelo1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mL_modelo1 == null)
            {
                return NotFound();
            }

            return View(mL_modelo1);
        }

        // GET: ML_modelo1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ML_modelo1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MLNombre,MLEdad,MLDireccion,MLDepartamento,MLFechaNacimiento,MLIsCliente,MLSaldo")] ML_modelo1 mL_modelo1)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mL_modelo1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mL_modelo1);
        }

        // GET: ML_modelo1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mL_modelo1 = await _context.ML_modelo1.FindAsync(id);
            if (mL_modelo1 == null)
            {
                return NotFound();
            }
            return View(mL_modelo1);
        }

        // POST: ML_modelo1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MLNombre,MLEdad,MLDireccion,MLDepartamento,MLFechaNacimiento,MLIsCliente,MLSaldo")] ML_modelo1 mL_modelo1)
        {
            if (id != mL_modelo1.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mL_modelo1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ML_modelo1Exists(mL_modelo1.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mL_modelo1);
        }

        // GET: ML_modelo1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mL_modelo1 = await _context.ML_modelo1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mL_modelo1 == null)
            {
                return NotFound();
            }

            return View(mL_modelo1);
        }

        // POST: ML_modelo1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mL_modelo1 = await _context.ML_modelo1.FindAsync(id);
            if (mL_modelo1 != null)
            {
                _context.ML_modelo1.Remove(mL_modelo1);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ML_modelo1Exists(int id)
        {
            return _context.ML_modelo1.Any(e => e.Id == id);
        }
    }
}

MaLopez_Examen1P/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">MATIAS LOPEZ</h1>
    <h2 class="display-4">PROGRAMACION IV</h2>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MaLopez_Examen1P/Views/ML_modelo1/Create.cshtml
@model MaLopez_Examen1P.Models.ML_modelo1

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ML_modelo1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MLNombre" class="control-label"></label>
                <input asp-for="MLNombre" class="form-control" />
                <span asp-validation-for="MLNombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MLEdad" class="control-label"></label>
                <input asp-for="MLEdad" class="form-control" />
                <span asp-validation-for="MLEdad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MLDireccion" class="control-label"></label>
                <input asp-for="MLDireccion" class="form-control" />
                <span asp-validation-for="MLDireccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MLDepartamento" class="control-label"></label>
                <input asp-for="MLDepartamento" class="form-control" />
                <span asp-validation-for="MLDepartamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MLFechaNacimiento" class="control-label"></label>
                <input asp-for="MLFechaNacimiento" class="form-control" />
                <span asp-validation-for="MLFechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="MLIsCliente" /> @Html.DisplayNameFor(model => model.MLIsCliente)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="MLSaldo" class="control-label"></label>
                <input asp-for="MLSaldo" class="form-control" />
                <span asp-validation-for="MLSaldo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MaLopez_Examen1P/Views/ML_modelo1/Delete.cshtml
@model MaLopez_Examen1P.Models.ML_modelo1

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ML_modelo1</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLEdad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLEdad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLDireccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLDireccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLDepartamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLDepartamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLFechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLFechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLIsCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLIsCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLSaldo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLSaldo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MaLopez_Examen1P/Views/ML_modelo1/Details.cshtml
@model MaLopez_Examen1P.Models.ML_modelo1

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ML_modelo1</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLEdad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLEdad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLDireccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLDireccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLDepartamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLDepartamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLFechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLFechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLIsCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLIsCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MLSaldo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MLSaldo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MaLopez_Examen1P/Views/ML_modelo1/Edit.cshtml
@model MaLopez_Examen1P.Models.ML_modelo1

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ML_modelo1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MLNombre" class="control-label"></label>
                <input asp-for="MLNombre" class="form-control" />
                <span asp-validation-for="MLNombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MLEdad" class="control-label"></label>
                <input asp-for="MLEdad" class="form-control" />
                <span asp-validation-for="MLEdad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MLDireccion" class="control-label"></label>
                <input asp-for="MLDireccion" class="form-control" />
                <span asp-validation-for="MLDireccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MLDepartamento" class="control-label"></label>
                <input asp-for="MLDepartamento" class="form-control" />
                <span asp-validation-for="MLDepartamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MLFechaNacimiento" class="control-label"></label>
                <input asp-for="MLFechaNacimiento" class="form-control" />
                <span asp-validation-for="MLFechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="MLIsCliente" /> @Html.DisplayNameFor(model => model.MLIsCliente)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="MLSaldo" class="control-label"></label>
                <input asp-for="MLSaldo" class="form-control" />
                <span asp-validation-for="MLSaldo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MaLopez_Examen1P/Views/ML_modelo1/Index.cshtml
@model IEnumerable<MaLopez_Examen1P.Models.ML_modelo1>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MLNombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MLEdad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MLDireccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MLDepartamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MLFechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MLIsCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MLSaldo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MLNombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MLEdad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MLDireccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MLDepartamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MLFechaNacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MLIsCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MLSaldo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MaLopez_Examen1P/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MaLopez_Examen1P</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MaLopez_Examen1P.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MaLopez_Examen1P</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ML_modelo1" asp-action="Index">Datos</a>
                        </li>
                        
               
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MaLopez_Examen1P - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>